#!/bin/sh

# USAGE: git alias <name(s)>
#  print the indicated git alias


while (( $# ))
do
    case $1 in
        --all|-a)
            _xtool_alias_print=1
            items+=( $(git config --includes --get-regexp --name-only '^alias\.' ) )
            ;;
        --no-deps)
            _xtool_alias_no_deps=1
            ;;
        --print|-p)
            _xtool_alias_print=1
            ;;
        --)
            shift
            items+=( "$@" )
            break
            ;;
        *)
            items+=( "$1" )
            ;;
    esac
    shift
done

for name in "${items[@]}"
do
    name="${name#alias.}";
    body="$(git config --includes --show-origin --get "alias.${name}")"
    [[ -z "$body" ]] && echo "no such alias: $name" && exit 1
    
    body="$(sed -e 's/^file:\([^ ]*\)\t/\1\n/' <<<"$body")"
    source="$(head -1 <<<"$body")"
    body="$(tail -n +2 <<<"$body")"

    if [[ "$body" =~ ^'xtool ' ]]
    then
        file=$(echo $body | cut -d' ' -f2)
        bat "$HOME/.git_tools/$file" --file-name="$source -> [alias.$name] -> $HOME/.git_tools/$file"
    else
        shfmt <<<"$body" | bat --language=sh --file-name="$source -> [alias.$name]"
    fi
done
