#!/bin/sh

# USAGE: git rollback [commit-ish] [n]
#  undo the last (n) commits while preserving the working tree (defaults to undo the most recent commit)

if [[ "$1" =~ ^[0-9]{1,7}$ ]]
then
	commit='HEAD'
	amount="$1"
else
	commit=$1
	amount=$2
fi

git reset --mixed "${commit:-HEAD}~${amount:-1}";
